import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { Store } from '../dist/store.js';
test('real stdio MCP handshake, discovery, retrieval, and validation errors',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'cground-mcp-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));await fs.mkdir(path.join(root,'app'));await fs.writeFile(path.join(root,'app/a.txt'),'format=v1');
 const store=new Store(root);await store.approveDefinitions([{id:'app',title:'Application',scope:'Application schemas and contracts.',excludes:'CI configuration.',chapters:[{id:'overview',title:'Overview',scope:'Application schemas and contracts.',excludes:'CI configuration.',paths:['app']}]}]);
 const client=new Client({name:'beta-test',version:'1.0.0'});const transport=new StdioClientTransport({command:process.execPath,args:[path.resolve('dist/cli.js'),'serve','--root',root],stderr:'pipe'});await client.connect(transport);t.after(()=>client.close());
 const manifest=JSON.parse(await fs.readFile(new URL('../package.json',import.meta.url),'utf8'));
 assert.equal(client.getServerVersion().version,manifest.version);
 const listed=await client.listTools();assert.equal(listed.tools.length,13);assert.ok(!listed.tools.some(x=>/create|approve|seed/.test(x.name)));
 const result=await client.callTool({name:'list_pillars',arguments:{}});assert.match(result.content[0].text,/Application/);
 const index=await client.callTool({name:'list_chapters',arguments:{pillarId:'app'}});assert.match(index.content[0].text,/app\/overview/);
 const chapter=await client.callTool({name:'read_chapter',arguments:{chapterId:'app/overview'}});assert.match(chapter.content[0].text,/unpopulated/);
 const owner=await client.callTool({name:'ownership_map',arguments:{path:'app/a.txt'}});assert.match(owner.content[0].text,/registered-path/);
 const start=await client.callTool({name:'start_here',arguments:{path:'app/a.txt'}});assert.match(start.content[0].text,/source of truth/);
 const graph=await client.callTool({name:'pillar_graph',arguments:{pillarId:'app'}});assert.equal(JSON.parse(graph.content[0].text).total,0);
 const tidy=await client.callTool({name:'tidy_plan',arguments:{target:'app'}});assert.equal(JSON.parse(tidy.content[0].text).writesKnowledge,false);
 const checklist=await client.callTool({name:'review_checklist',arguments:{chapterIds:['app/overview'],touchedPaths:['app/a.txt']}});assert.equal(checklist.isError,undefined);
 const missing=await client.callTool({name:'list_chapters',arguments:{pillarId:'missing'}});assert.equal(missing.isError,true);
 const fact=value=>({id:'format',statement:`The application accepts ${value} events.`,evidence:[{path:'app/a.txt',quote:`format=${value}`}],sourceScope:['app/a.txt'],dependsOn:[]});
 await store.seed('app/overview',[fact('v1')]);await fs.writeFile(path.join(root,'app/a.txt'),'format=v2');
 await fs.readFile(path.join(root,'app/a.txt'),'utf8');
 const prepared=await client.callTool({name:'prepare_update',arguments:{chapterId:'app/overview',touchedPaths:['app/a.txt'],verification:{sourceFiles:['app/a.txt'],documentFiles:[]},reviews:[{chapterId:'app/overview',expectedRevision:1,reviewedFactIds:['format'],invalidatedFactIds:['format'],facts:[fact('v2')],reason:'The verified application contract now accepts v2 events.'}]}});
 assert.equal(prepared.isError,undefined);const proposal=JSON.parse(prepared.content[0].text);
 const committed=await client.callTool({name:'commit_update',arguments:{proposalId:proposal.proposalId}});assert.equal(committed.isError,undefined);
 assert.equal(store.chapter(await store.read(),'app/overview').facts[0].statement,fact('v2').statement);
});
