import { z } from 'zod';
export const relativePath = z.string().min(1).refine(p => !p.startsWith('/') && !p.includes('\\') && !p.split('/').some(s => s === '..' || s === '.' || s === '') && !/^[A-Za-z]:/.test(p), 'Use a repository-relative path without traversal');
const id = z.string().regex(/^[a-z0-9][a-z0-9-]*$/);
export const chapterKey = z.string().regex(/^[a-z0-9][a-z0-9-]*\/[a-z0-9][a-z0-9-]*$/);
export const factKey = z.string().regex(/^[a-z0-9][a-z0-9-]*\/[a-z0-9][a-z0-9-]*\/[a-z0-9][a-z0-9-]*$/);
export const Evidence = z.object({ path: relativePath, quote: z.string().trim().min(1).max(1200) }).strict();
const LegacyFact = z.object({ id, statement: z.string().trim().min(8).max(2000), evidence: z.array(Evidence).min(1).max(8) }).strict();
export const Fact = LegacyFact.extend({sourceScope:z.array(relativePath).min(1),dependsOn:z.array(factKey).default([])}).strict();
const Boundary = z.object({ id, title: z.string().trim().min(3).max(100), scope: z.string().trim().min(12).max(800), excludes: z.string().trim().min(3).max(800) }).strict();
export const ChapterDefinition = Boundary.extend({ paths: z.array(relativePath).min(1).max(30) }).strict();
export const Chapter = ChapterDefinition.extend({ revision: z.number().int().positive(), facts: z.array(Fact), sources: z.record(z.string()), dependencyFingerprints: z.record(z.string()).default({}) }).strict();
export const PillarDefinition = Boundary.extend({ chapters: z.array(ChapterDefinition).min(1) }).strict();
export const Pillar = Boundary.extend({ chapters: z.array(Chapter).min(1) }).strict();
export const Registry = z.object({ schemaVersion: z.literal(2), pillars: z.array(Pillar) }).strict();
export const Maintenance = z.object({factId:id, action:z.enum(['correct','merge','remove','tighten']), reason:z.string().trim().min(12).max(1000), replacement:factKey.optional()}).strict();
export const Review = z.object({ chapterId: chapterKey, expectedRevision: z.number().int().positive(), invalidatedFactIds: z.array(z.string()), reviewedFactIds: z.array(z.string()), facts: z.array(Fact), reason: z.string().trim().min(12).max(1000), maintenance:z.array(Maintenance).optional() }).strict();
export const Verification = z.object({sourceFiles:z.array(relativePath), documentFiles:z.array(relativePath)}).strict();
export const Update = z.object({ chapterId: chapterKey, factIds:z.array(id).min(1).optional(), touchedPaths: z.array(relativePath), reviews: z.array(Review).min(1), verification:Verification, tidyId:z.string().uuid().optional() }).strict();
export const LegacyRegistry = z.object({ schemaVersion: z.literal(1), pillars: z.array(Boundary.extend({ paths: z.array(relativePath).min(1).max(30), revision:z.number().int().positive(), facts:z.array(LegacyFact), sources:z.record(z.string()) }).strict()) }).strict();
export type Definition = z.infer<typeof PillarDefinition>;
export type ChapterRecord = z.infer<typeof Chapter>;
export type RegistryRecord = z.infer<typeof Registry>;
export type UpdateRequest = z.infer<typeof Update>;
export function unique(values: string[], label: string) { if (new Set(values).size !== values.length) throw new Error(`Duplicate ${label}`); }
